Repository tbz-nerd-ag/e-paper-main, pull requests merged in 2024-12, with the labels that each got.

#3 fixed untis login
  UNTIS-WRAPPER/untis.py
  config.json
Labels: bug, feature

#7 Make the the imagegen for one hour functional ~yeah pizza ^^
  IMAGEGEN/imagegen2.py
  UNTIS-WRAPPER/untis.py
  UNTIS-WRAPPER/untis2imagegen.py
  config.json
Labels: bug, feature

#10 mainly: add a list for cache; and a little bit bug fixing ~rawr
  IMAGEGEN/imagegen2.py
  UNTIS-WRAPPER/rooms.json
  UNTIS-WRAPPER/untis.py
  UNTIS-WRAPPER/untis2imagegen.py
Labels: bug, feature

#14 add logging and make the demo image a little bit more functional
  UNTIS-WRAPPER/log/1138-2024-12-12.log
  UNTIS-WRAPPER/untis.py
Labels: feature

#13 Jetzt mal endlich Advanced Doku für Imagegen
  .gitignore
  IMAGEGEN/imagegen2.py
  ROOMIMAGES/2.312
  UNTIS-WRAPPER/untis2imagegen.py
Labels: documentation, enhancement

#15 bug fixed - untis2imagegen.py
  UNTIS-WRAPPER/graustufenbild_demo.png
  UNTIS-WRAPPER/log/1138-2024-12-12.log
  UNTIS-WRAPPER/untis.py
  UNTIS-WRAPPER/untis2imagegen.py
Labels: bug

#17 add .env for login data and a little fix for untis2image
  .gitignore
  UNTIS-WRAPPER/graustufenbild_demo.png
  UNTIS-WRAPPER/log/1619-2024-12-12.log
  UNTIS-WRAPPER/untis.py
  UNTIS-WRAPPER/untis2imagegen.py
  config.json
Labels: bug, feature

#18 HOTFIX: username error on windows and linux systems
  UNTIS-WRAPPER/untis.py
Labels: bug

#24 add double hours ~yeah pizza
  UNTIS-WRAPPER/untis.py
Labels: feature

#28 Config "Wartungsmodus" für imagegen2.py hinzugefügt
  IMAGEGEN/imagegen2.py
  config.json
Labels: documentation, enhancement, feature

#29 Dashy Config Backup
  UI/Dashy/config.yml
  UI/Dashy/displayStat.yml
Labels: wontfix

#30 Maintenance Hotfix + webhook .env integration
  IMAGEGEN/imagegen2.py
  UI/batts_webhook.py
  UNTIS-WRAPPER/untis.py
  config.json
Labels: documentation, enhancement

#31 webhook Connection Error Func eingefügt
  UI/batts_webhook.py
Labels: documentation, enhancement, feature

#32 A "few" changes - yeah
  UNTIS-WRAPPER/rooms.json
  UNTIS-WRAPPER/test.py
  UNTIS-WRAPPER/untis.py
  UNTIS-WRAPPER/untis2imagegen.py
Labels: bug, feature

#33 Stundenlänge und Abstände hinzugefügt (Fiebertraum)
  IMAGEGEN/imagegen2.py
  config.json
Labels: documentation, enhancement, help wanted

#34 Hotfix imagegen
  IMAGEGEN/imagegen2.py
Labels: documentation, enhancement
